src: add support for --ua-token
canonical/action-build pull request #14
Opened 2021-03-24 19:04 UTC by cjp256

WIP on the Snapcraft side, see: https://github.com/snapcore/snapcraft/pull/3488

Early opening here to get feedback on this approach (snapcraft-args could be used instead as it is a fairly limited use case?).

2021-04-05 10:01 UTC, jhenstridge commented
I think a special purpose input parameter is fine.  There's less opportunity for mistakes, and this should have more stability guarantees compared to the `--enable-experimental-*` flags I originally added `snapcraft-args` for.

One question: how sensitive are these tokens? If we don't want people checking them into their repository, then it would be good to include an example in the documentation that sets the parameter using a secret.  Of course, using a secret won't help for workflows triggered by pull requests. I'm not sure how we'd handle that case other than hard coding the token in the workflow.

2021-04-05 13:14 UTC, cjp256 commented
> One question: how sensitive are these tokens? If we don't want people checking them into their repository, then it would be good to include an example in the documentation that sets the parameter using a secret.

They are secrets - documenting it as such is a good idea.  I'll do that.

> Of course, using a secret won't help for workflows triggered by pull requests. I'm not sure how we'd handle that case other than hard coding the token in the workflow.

I don't know that there's much that can be done about the PR issue.  I think this suffers the same fate as any GitHub CI pipeline requiring secrets unfortunately :-(  That is, avoid it at all costs and update your `base` :rofl:

2021-04-20 14:21 UTC, cjp256 commented
The upstream PR has landed, so I've opened this up.  Note that it won't work until it lands in the Snapcraft's stable channel.

2021-04-21 10:50 UTC, jhenstridge requested changes
This looks good.  I've got one small change request w.r.t. the documentation, but the code looks good.

I don't think we need to wait for a stable Snapcraft release supporting the feature before merging, since (a) all existing workflows will continue to run as they do now, and (b) users can use `snapcraft-channel: edge` if they want to use it now.

2021-04-21 10:50 UTC, jhenstridge commented on src/build.ts
> +    uaToken: string
The list of constructor arguments is starting to get a bit unwieldly here.  I don't think it's worth blocking this PR to clean it up, but it's probably something I should put on my own todo list.

2021-04-21 10:50 UTC, jhenstridge commented on README.md
> +```
Could you leave a note indicating that secrets are not available for workflows triggered by pull_request events? (at least for public repos: it can be enabled for private repos).  There are going to be users who run into this limitation when adopting this feature, so it would be better to be up front about it.

2021-04-27 04:31 UTC, merged